### ISSUE TITLE
What model is better? parameters and details about it

### ISSUE THREAD

**Issue by arsenyzb** [MANASLU8/CoreNLPRusModels#2]
Здравствуйте! 
Следуя из прошлого вопроса: 

1) Как Вы сказали, в моделях вот это разные виды тэггера: russian-ud-pos.tagger - просто тэггер, russian-ud-mfmini.tagger - с основным списком morphological features, russian-ud-mf.tagger - с полным списком morphological features. То есть тут в первом тэггере основной набор морфологий, а в двух других там еще и различают всякие вещи вроде числа падежа и так далее, но в чем тогда разница между последними двумя, не могли бы Вы пояснить на примере? Я понял, что последняя модель распознает максимально морфологические особенности, но по кодировке это не очевидно (если смотреть пример маппинга для моделей). Не могли бы Вы пояснить на каком-нибудь примере в чем лучше одна и другая?

2) Я посмотрел пример маппинга для russian-ud-mf.tagger https://github.com/MANASLU8/CoreNLP/blob/master/src/edu/stanford/nlp/international/russian/process/RussianMorphoAnnotator.java
Но тут у меня возник ряд вопросов:
а) Что значит Animacy и соответственно подполя этого поля - Anim и Inan? 
б) Зачем  в NOUN, ADJ и других частях речи нужен параметр Foreign если у него только одно состояние - "Yes" (насколько я понимаю, он определяет является ли слово инородным, то есть есть оно в словаре или нет, в противном случае поправьте меня пожалуйста)в) А также, зачем в параметре падежей "Case" 8 значений, ведь падежей всего 6 (Я понял, что Acc - винительный падеж, Dat - дательный Nom - именительный, Gen - родительный, однако что означают остальные Inc, Loc, Par, Voc - все же неясно. Я попытался выяснить это с помощью russian-ud-mf.tagger, однако возникли противоречивые ситуации, и я все же хотел бы узнать от Вас, что они обозначают)?
г) Также что обозначают Cnd, Imp, Ind для поля "Case"(то есть для склонения. Я также пытался выяснить это с помощью тэггера и яндекс переводчика, но также у меня возникли спорные ситуации в интерпретации этих обозначений)?
д) А также что значат поля Voice? Насколько я понимаю, это какая-то интерпретация настроения?

е) Также я бы хотел узнать точно, так как опять же не уверен, что означает поле PROPN среди всех частей речи? Насколько я понимаю, это имя собственное, однако можно ли для данного имени собственного сделать какой-то интерпретатор определения места или человека и так далее? Я имею ввиду извлечение именованных сущностей. Или может у Вас уже есть какие-то наработки по этой части? Был бы признателен, если бы Вы рассказали мне о них или дали бы какую-нибудь ссылку на источник.

3) Также, насколько Вы сказали, модели, сделанные Вами: nndep.rus.model81_mf.txt, nndep.rus.model90.9_88.6.txt, nndep.rus.modelMFAr100HS400_81.txt, и nndep.rus.modelMFWiki100HS400_80.txt  отличаются тем, чтоиспользуют разные embedding'и при обучении моделей, количеством скрытых слоев (hidden layer), точностью и используемым тэггером, так вот вопросы:
-Какими embedding'ами в каких моделях пользовались?
-Какую точность показали каждая из них?
-Какие скрытые слои, сколько слоев в каждой из них?
-И конечно,в какой из них, какой теггер использовался?

**Comment by kamivao** [comment]
Здравствуйте, Арсений!
1, 2. Мы использовали обозначения грамматических категорий и синтаксических отношений из стандарта Universal Dependencies: http://universaldependencies.org/
3. Все описано в статье, вот ссылка https://link.springer.com/chapter/10.1007/978-3-319-69548-8_8
